### ISSUE TITLE
[ERROR] Bad log priority on force update

### ISSUE THREAD

**Issue by ashleyse2016** [SpamExperts/cpanel-addon#40]
### Version information
```
Information
Controlpanel: Cpanel v11.66.0.34
PHP version: 5.6.30
Addon version: 3.0.96562
Diagnostics
```

### Steps to replicate

 1.For update via command line
```
root@stable [~]# wget -N https://download.seinternal.com/integration/installers/cpanel/installer.sh && bash installer.sh
```

### Actual result
```
--2017-12-01 00:00:55--  https://download.seinternal.com/integration/installers/cpanel/installer.sh
Reusing existing connection to download.seinternal.com:443.
HTTP request sent, awaiting response... 200 OK
Length: 7579 (7.4K) [application/octet-stream]
Saving to: “installer.sh”

100%[====================================================================================================================================================>] 7,579       --.-K/s   in 0s      

2017-12-01 00:00:55 (344 MB/s) - “installer.sh” saved [7579/7579]

Installing ProSpamFilter for cPanel..
Access hash for WHM API already exists, skipping step.
[INFO] This system will install Professional Spam Filter v3.0.96562 for cpanel
[INFO] No need to update the structure of the addon, we are already past the upgrade point.
[INFO] Running selfcheck...
[OK] Finished without errors
[INFO] Copying files to destination.
[INFO] Cleaning up old folder (/usr/local/prospamfilter)..
[OK] Done
[INFO] Creating new folder (/usr/local/prospamfilter)..
[OK] Done
[INFO] Copying files from '/usr/src/prospamfilter' to '/usr/local/prospamfilter'...
[OK] Done
[INFO] Setting tmp folder permissions
[OK] Done
[INFO] Prepopulating config folder
[OK] Done
[INFO] Symlinking cPanel addon to webdirs
[INFO] Symlinking cPanel addon to webdir paper_lantern
[INFO] Symlinking cPanel addon to webdir x3
[INFO] Symlinking cPanel addon to webdir x3mail
[INFO] Symlinking WHM addon to webdir
[INFO] Symlinking WHM addon icons to webdir
[INFO] Symlinking cPanel addon icons to webdir
[INFO] Symlinking cPanel addon icons to webdir
[INFO] Making WHM addon executable
[INFO] Symlinking WHM icon to webdir
[INFO] Configuration file '/etc/prospamfilter/settings.conf' already exists.
[INFO] Generating cPanel plugin configuration..
[INFO] Configuring brand
[OK] Done
[INFO] Registering hooks ...
Skipped hook Accounts::Create as it already exists.
Skipped hook Accounts::Remove as it already exists.
Skipped hook Accounts::Modify as it already exists.
Skipped hook Domain::park as it already exists.
Skipped hook Domain::unpark as it already exists.
Skipped hook Restore as it already exists.
Skipped hook Api2::AddonDomain::addaddondomain as it already exists.
Skipped hook Api2::AddonDomain::deladdondomain as it already exists.
Skipped hook Api2::SubDomain::addsubdomain as it already exists.
Skipped hook Api2::SubDomain::delsubdomain as it already exists.
Skipped hook Api2::CustInfo::savecontactinfo as it already exists.
Skipped hook Api2::Email::setmxcheck as it already exists.
[OK] Done.
[INFO] The WHM app in already registered in the AppConfig registry
[INFO] The Cpanel_paper_lantern app in already registered in the AppConfig registry
[INFO] The Cpanel_x3 app in already registered in the AppConfig registry
[INFO] The Cpanel_x3mail app in already registered in the AppConfig registry
[ERROR] Bad log priority
```

### Expected result

Complete install. 

### Other notes

Debug shows

```
Dec  1 00:15:02 stable ProSpamFilter[10139]: [Cpanel] Re-registering plugin for other themes & generating sprites.
Dec  1 00:16:56 stable ProSpamFilter[10139]: [Cpanel] Setting up brand name for the side-menu
Dec  1 00:16:56 stable ProSpamFilter[10139]: [Cpanel] Regenerating cpanelplugin has been completed.
Dec  1 00:16:57 stable ProSpamFilter[10139]: Bad log priority
Dec  1 00:16:57 stable ProSpamFilter[10139]: #0 /usr/src/prospamfilter/library/Installer/Installer.php(162): Zend_Log->__call('error', Array)#012#1 /usr/src/prospamfilter/library/Installer/Installer.php(162): SpamFilter_Logger->error('Failed to updat...')#012#2 /usr/src/prospamfilter/library/Installer/Installer.php(118): Installer_Installer->setUpApiTokens()#012#3 /usr/src/prospamfilter/library/Installer/Installer.php(52): Installer_Installer->doInstall()#012#4 /usr/src/prospamfilter/bin/install.php(77): Installer_Installer->install()#012#5 {main}
```
```
"/usr/local/cpanel/base/frontend/YES/branding/crimson_smoke/heading_sprites_bg_snap_to_smallest_width.png".

[2017-12-01 00:16:56 -0500] info [xml-api] Unknown app ("api_token_update") requested for this version (1) of the API. [api_token_update] version [1].
==> cpsrvd 11.66.0.34 started
==> cpsrvd: loading security policy....Done
==> cpsrvd: Setting up SSL support ... Done
==> cpsrvd: transferred port bindings
==> cpsrvd: bound to ports
```

**Comment by for93t** [comment]
Unfortunately current cPanel Stable (v66) does not allow editing tokens so the only way to have an access token with `all` permission is to recreate it (revoking the existing one).
